---    
# Install Helm 3 (if not already installed)
- name: Check Helm installation
  shell: helm version
  register: helm_result
  ignore_errors: true

- name: Create Helm 3 Installation script
  blockinfile:
    path: /tmp/get-helm.sh
    create: yes
    mode: 0755
    content: |
      curl -fsSL -o get-helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      chmod +x get-helm.sh
      ./get-helm.sh
  when: helm_result.rc != 0

- name: Launch Helm 3 Installation script
  shell: /tmp/get-helm.sh
  when: helm_result.rc != 0

- name: Clean helm installation files
  file: 
    path: get-helm.sh
    state: absent